version: "3"
volumes:
    mysql-data:
        driver: local

services:
    nginx:
        image: nginx
        container_name: "domestic-pay-nginx"
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php
        container_name: "domestic-pay-php"
        volumes:
            - ./:/var/www:cached
            - ~/.ssh:/root/.ssh

    mysql:
        platform: linux/x86_64 # M1チップ対応のため追記
        restart: always
        image: mysql:8.0
        container_name: "domestic-pay-mysql"
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: dev
        ports:
            - 33306:3306
        volumes:
            - mysql-data:/var/lib/mysql:cached